import React, { useState } from 'react';
import { 
  Citrus, 
  Sparkles, 
  RefreshCcw, 
  AlertCircle, 
  CheckCircle2, 
  Clock, 
  Sliders, 
  ShieldCheck,
  FileCheck
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { ImageDropzone } from '../components/ImageDropzone';
import { ProbabilityBar } from '../components/ProbabilityBar';
import { TreatmentCard } from '../components/TreatmentCard';
import { apiService, ApiError } from '../services/api';
import type { FruitPredictionResponse } from '../types/disease';

import { CITRUS_DISEASES } from '../data/diseaseDatabase';
import { useHistory } from '../context/HistoryContext';

export const FruitDetection: React.FC = () => {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<FruitPredictionResponse | null>(null);
  const [inferenceTime, setInferenceTime] = useState<number | null>(null);
  const { addRecord } = useHistory();

  const handleImageSelected = (file: File) => {
    setSelectedFile(file);
    setError(null);
    setResult(null);
    setInferenceTime(null);
  };

  const handleClear = () => {
    setSelectedFile(null);
    setError(null);
    setResult(null);
    setInferenceTime(null);
  };

  const handleAnalyze = async () => {
    if (!selectedFile) return;

    setIsLoading(true);
    setError(null);
    const startTime = performance.now();

    try {
      const data = await apiService.predictFruit(selectedFile);
      const duration = Math.round(performance.now() - startTime);
      setInferenceTime(duration);
      setResult(data);

      // Save to local history
      addRecord({
        type: 'fruit',
        predictedClass: data.predicted_class,
        confidence: data.confidence,
        probabilities: data.probabilities,
        filename: selectedFile.name,
      });
    } catch (err: unknown) {
      if (err instanceof ApiError) {
        setError(err.message);
      } else {
        setError('An unexpected error occurred while communicating with the fruit prediction service.');
      }
    } finally {
      setIsLoading(false);
    }
  };

  const diagnosedDisease = result
    ? CITRUS_DISEASES[result.predicted_class.toLowerCase()] || {
        id: result.predicted_class,
        name: `Citrus ${result.predicted_class}`,
        scientificName: 'Citrus Pathogen Specimen',
        category: 'fruit' as const,
        severity: result.predicted_class.toLowerCase() === 'healthy' ? 'healthy' as const : 'high' as const,
        description: 'Disease classification generated by ResNet-34 neural network model.',
        symptoms: ['Rind lesion or discoloration matching classification patterns.'],
        causes: ['Citrus orchard pathogen infection.'],
        treatments: ['Consult your regional agricultural extension advisor for appropriate spray schedules.'],
        prevention: ['Maintain sanitary harvesting practices and clean machinery.'],
        badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30'
      }
    : null;

  return (
    <div className="space-y-8 pb-12 text-left max-w-6xl mx-auto">
      {/* Title */}
      <div className="space-y-2">
        <div className="flex items-center gap-2 text-xs font-mono text-emerald-400">
          <Citrus className="w-4 h-4 text-amber-400" />
          <span>DEEP TRANSFER LEARNING ENGINE (RESNET-34)</span>
        </div>
        <h1 className="text-2xl sm:text-4xl font-extrabold text-white tracking-tight">
          Citrus Fruit Disease Diagnosis
        </h1>
        <p className="text-xs sm:text-sm text-slate-400 max-w-2xl leading-relaxed">
          Upload an image of a citrus fruit specimen to identify Black Spot, Citrus Canker, 
          Greening (Huanglongbing), or confirm a Healthy fruit.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Left Column: Upload and Controls */}
        <div className="lg:col-span-6 space-y-6">
          <div className="bg-slate-900/60 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-5">
            <h3 className="text-sm font-semibold uppercase tracking-wider text-slate-300 flex items-center gap-2">
              <FileCheck className="w-4 h-4 text-emerald-400" />
              Upload Fruit Specimen
            </h3>

            <ImageDropzone
              onImageSelected={handleImageSelected}
              selectedFile={selectedFile}
              onClear={handleClear}
              disabled={isLoading}
            />

            {/* Action buttons */}
            <div className="flex gap-3 pt-2">
              <button
                type="button"
                onClick={handleAnalyze}
                disabled={!selectedFile || isLoading}
                className={`flex-1 py-3 px-5 rounded-xl font-bold text-sm transition-all flex items-center justify-center gap-2 shadow-lg ${
                  !selectedFile || isLoading
                    ? 'bg-slate-800 text-slate-500 cursor-not-allowed border border-slate-800'
                    : 'bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-slate-950 shadow-emerald-500/20 hover:scale-[1.01] cursor-pointer'
                }`}
              >
                {isLoading ? (
                  <>
                    <RefreshCcw className="w-4 h-4 animate-spin" />
                    <span>Processing Neural Network...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4" />
                    <span>Run AI Disease Classification</span>
                  </>
                )}
              </button>

              {selectedFile && !isLoading && (
                <button
                  type="button"
                  onClick={handleClear}
                  className="px-4 py-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-sm font-medium border border-slate-700 transition-colors cursor-pointer"
                >
                  Reset
                </button>
              )}
            </div>

            {/* Error Message */}
            {error && (
              <motion.div
                initial={{ opacity: 0, y: 5 }}
                animate={{ opacity: 1, y: 0 }}
                className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs sm:text-sm flex items-start gap-3"
              >
                <AlertCircle className="w-5 h-5 text-rose-400 shrink-0 mt-0.5" />
                <div>
                  <p className="font-semibold text-rose-200">Inference Error</p>
                  <p className="mt-0.5 leading-relaxed">{error}</p>
                </div>
              </motion.div>
            )}
          </div>

          {/* Model Specs Card */}
          <div className="p-5 rounded-2xl bg-slate-900/40 border border-slate-800/80 text-xs text-slate-400 space-y-2">
            <div className="flex items-center justify-between text-slate-300 font-semibold mb-1">
              <span className="flex items-center gap-1.5">
                <Sliders className="w-3.5 h-3.5 text-emerald-400" />
                Inference Protocol
              </span>
              <span className="font-mono text-emerald-400">POST /predict</span>
            </div>
            <p>
              Preprocessed via bilinear resize to 256px with 224px center crop and standard ImageNet normalization. 
              Output computed via softmax across 4 target classes.
            </p>
          </div>
        </div>

        {/* Right Column: Diagnostic Output */}
        <div className="lg:col-span-6 space-y-6">
          <AnimatePresence mode="wait">
            {isLoading ? (
              <motion.div
                key="loading"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="p-12 rounded-3xl border border-slate-800 bg-slate-900/50 flex flex-col items-center justify-center text-center space-y-4 min-h-[420px]"
              >
                <div className="relative">
                  <div className="w-16 h-16 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400 animate-pulse">
                    <Citrus className="w-8 h-8" />
                  </div>
                  <RefreshCcw className="w-6 h-6 text-emerald-400 animate-spin absolute -top-2 -right-2" />
                </div>
                <h3 className="text-lg font-bold text-white">Analyzing Citrus Rind Morphology...</h3>
                <p className="text-xs text-slate-400 max-w-xs leading-relaxed">
                  Executing forward pass on ResNet-34 convolutional backbone. Computing softmax disease distribution.
                </p>
              </motion.div>
            ) : result && diagnosedDisease ? (
              <motion.div
                key="result"
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                className="space-y-6"
              >
                {/* Result Card */}
                <div className="p-6 rounded-3xl bg-slate-900/80 border border-slate-700/80 shadow-2xl space-y-5">
                  <div className="flex items-center justify-between border-b border-slate-800 pb-4">
                    <span className="text-xs uppercase font-mono tracking-wider text-slate-400 flex items-center gap-1.5">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                      Classification Output
                    </span>
                    {inferenceTime && (
                      <span className="text-xs font-mono text-slate-400 flex items-center gap-1">
                        <Clock className="w-3.5 h-3.5 text-slate-500" />
                        {inferenceTime} ms
                      </span>
                    )}
                  </div>

                  <div className="flex flex-wrap items-center justify-between gap-4">
                    <div>
                      <p className="text-xs text-slate-400 uppercase tracking-wider font-semibold">
                        Identified Condition
                      </p>
                      <h2 className="text-2xl sm:text-3xl font-extrabold text-white capitalize mt-0.5">
                        {result.predicted_class}
                      </h2>
                    </div>

                    <div className="text-right">
                      <p className="text-xs text-slate-400 uppercase tracking-wider font-semibold">
                        Model Confidence
                      </p>
                      <p className="text-2xl sm:text-3xl font-mono font-bold text-emerald-400">
                        {(result.confidence * 100).toFixed(1)}%
                      </p>
                    </div>
                  </div>

                  {/* Probability Breakdown */}
                  <div className="pt-2">
                    <h4 className="text-xs uppercase font-semibold text-slate-400 tracking-wider mb-3">
                      Softmax Probability Distribution
                    </h4>
                    <ProbabilityBar
                      probabilities={result.probabilities}
                      predictedClass={result.predicted_class}
                    />
                  </div>
                </div>

                {/* Treatment Card */}
                <TreatmentCard disease={diagnosedDisease} confidence={result.confidence} />
              </motion.div>
            ) : (
              <div className="p-12 rounded-3xl border border-dashed border-slate-800 bg-slate-900/30 flex flex-col items-center justify-center text-center space-y-3 min-h-[420px]">
                <div className="w-14 h-14 rounded-2xl bg-slate-900 border border-slate-800 flex items-center justify-center text-slate-500">
                  <ShieldCheck className="w-7 h-7" />
                </div>
                <h3 className="text-base font-bold text-slate-300">Awaiting Specimen Upload</h3>
                <p className="text-xs text-slate-500 max-w-xs leading-relaxed">
                  Upload a fruit photo and click "Run AI Disease Classification" to generate pathological breakdown and treatment recommendations.
                </p>
              </div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
};
